[versions]
kotlin = "2.0.21"
agp = "8.9.3"

hilt = "2.51.1"
hiltNavigationCompose = "1.3.0"

android-compose = "2024.06.00"
activityCompose = "1.10.0"
appcompat = "1.7.1"
coreKtx = "1.16.0"
lifecycle = "2.8.4"
lifecycleRuntimeKtx = "2.9.4"
android-navigation = "2.9.5"
android-tv = "1.0.0-alpha07"

materialIcons = "1.6.8"
coil = "3.2.0"
smbj = "0.14.0"
snakeyaml = "2.2"
timber = "5.0.1"

[libraries]
# AndroidX
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "android-compose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }

androidx-tv-foundation = { group = "androidx.tv", name = "tv-foundation", version.ref = "android-tv" }
androidx-tv-material = { group = "androidx.tv", name = "tv-material", version.ref = "android-tv" }

androidx-navigation-compose-android = { group = "androidx.navigation", name = "navigation-compose-android", version.ref = "android-navigation" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# Utilities & Third-Party
material-icons = { group = "androidx.compose.material", name = "material-icons-extended-android", version.ref = "materialIcons" }
coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
smbj = { module = "com.hierynomus:smbj", version.ref = "smbj" }
snakeyaml = { group = "org.yaml", name = "snakeyaml", version.ref = "snakeyaml" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# Tests
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
androidx-navigation-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "android-navigation" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
